# Generated by Django 6.0.2 on 2026-03-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('FullName', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=10)),
                ('BirthDate', models.DateField()),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseCategory', models.CharField(max_length=50)),
                ('ExpenseAmount', models.FloatField()),
                ('ExpenseDescription', models.CharField(max_length=200)),
                ('ExpenseDate', models.DateField(blank=True, null=True)),
                ('NoteDate', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.userdetail')),
            ],
        ),
    ]
