# Generated by Django 6.0.2 on 2026-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='FullName',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
