# Generated by Django 6.0.2 on 2026-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_userdetail_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='MonthlySalary',
            field=models.FloatField(default=0.0),
        ),
    ]
