# Generated by Django 6.0.2 on 2026-03-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_userdetail_monthlysalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpulseBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.FloatField()),
                ('Category', models.CharField(default='Other', max_length=50)),
                ('Note', models.CharField(blank=True, default='', max_length=500)),
                ('IntendedDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('bought', 'Bought'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ExpiresAt', models.DateTimeField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulse_buys', to='expense.userdetail')),
            ],
        ),
    ]
